name: PASK Task Management
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: https://vercel-todo-server.vercel.app/api/update?id=aI0x5DmJwAdvmbcAexxSFTfbgos1&project=Online-Auction&username=dom991
          method: POST
